### ISSUE TITLE
configuration file converter

### ISSUE THREAD

**Issue by masthisis** [mahdibland/ShadowsocksAggregator#2]
i need to convert the clash-config.yml to napsternetv ios config file how can i do it ?

**Comment by mahdibland** [comment]
not sure about the napsternetv, I don't have ios to test it and the converter that I use does not support napsternetv conversion.
if it allows you to import from the clipboard then convert the clash config to raw links using ["subconveter"](https://github.com/tindy2013/subconverter)

**Comment by dickymuliafiqri** [comment]
> i need to convert the clash-config.yml to napsternetv ios config file how can i do it ?


I do have support for various format that (maybe) compatible with napsternetv.
https://github.com/dickymuliafiqri/Spider/tree/main/result

And thanks to @mahdibland, my project originally inspired from your repo.
